name: Build Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-maven-*

      - name: Create LambdaUrlCreator Artifacts
        run: |
          cd LambdaUrlCreator
          mvn clean package

      - name: Create LambdaUrlRedirector Artifacts
        run: |
          cd LambdaUrlRedirector
          mvn clean package

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: |
            LambdaUrlCreator/target/*.jar
            LambdaUrlRedirector/target/*-shaded.jar
